# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/dataidea-typescript',
                'doc_host': 'https://dataideaorg.github.io',
                'git_url': 'https://github.com/dataideaorg/dataidea-typescript',
                'lib_path': 'dataidea_typescript'},
  'syms': {'dataidea_typescript.core': {'dataidea_typescript.core.foo': ('core.html#foo', 'dataidea_typescript/core.py')}}}
